### ISSUE TITLE
ruboty-slack_rtm に移行する

### ISSUE THREAD

**Issue by masutaka** [feedforce/feedforce-ruboty#100]
[現在の ruboty-slack](https://github.com/feedforce/feedforce-ruboty/blob/eacdf36938300c3096c0b466d48b97789d2e797c/Gemfile#L19) と比べて良いところ。

* 実際のアカウントではなく、[BOT アカウントを使う](https://my.slack.com/services/new/bot)ので、料金がかからない
* 環境変数 `$SLACK_ROOM` をメンテナンスしなくて良い。使いたい channel に BOT を invite するだけ

feedkun の名前そのままに、BOT アカウントに移行できるかが鍵かなあ？

* https://github.com/r7kamura/ruboty-slack
* https://github.com/rosylilly/ruboty-slack_rtm

**Comment by masutaka** [comment]
`Subject: Saying goodbye to Slack’s IRC and XMPP gateways` というメールが来た。

ruboty-slack から別のアダプタに移行しないと、2018/5/15 に使えなくなってしまう。

**Comment by tsub** [comment]
> feedkun の名前そのままに、BOT アカウントに移行できるかが鍵かなあ？

試しに個人 Slack で同じ操作を再現してみた。

すでにユーザーとして存在するユーザー名と同じ名前の Bot ユーザーを作成しようとすると以下のようにエラーが出てしまった。

<img width="1017" alt="_2018_03_25_11_05" src="https://user-images.githubusercontent.com/10208211/37870907-a2ee3d8c-301c-11e8-8f18-221a71e9c9a7.png">

---

その次に個人 Slack で `test` というユーザーを作り、そのユーザーを Deactivate してから `test` という Bot ユーザーを作ってみたところこちらは問題なく作成できた。

<img width="986" alt="_2018_03_25_11_18" src="https://user-images.githubusercontent.com/10208211/37870973-4ea4d54a-301e-11e8-953d-1ab2339df508.png">

<img width="1010" alt="_2018_03_25_11_19" src="https://user-images.githubusercontent.com/10208211/37870979-5d916bb8-301e-11e8-9c87-831e51900873.png">

そのため、`feedkun` というユーザーを一度 Deactivate にし、`feedkun` という Bot ユーザーを作れば同名の名前で移行はできそうである。

**Comment by tsub** [comment]
> `Subject: Saying goodbye to Slack’s IRC and XMPP gateways` というメールが来た。
>
> ruboty-slack から別のアダプタに移行しないと、2018/5/15 以降使えなくなってしまう。

気づいたら 5/15 を迎えていて XMPP gateways が使えなくなっていた...

移行を始めます。

まずは gem を `ruboty-slack` → `ruboty-slack_rtm` に置き換えるところから。

**Comment by tsub** [comment]
会社の Slack ワークスペースで[以前の検証](https://github.com/feedforce/feedforce-ruboty/issues/100#issuecomment-375940191)と同じことをやったらできなかった :innocent:

![image](https://user-images.githubusercontent.com/10208211/40092995-3db3d0f0-58fb-11e8-9c57-d79f4abcc101.png)

**Comment by tsub** [comment]
旧 `@feedkun` をリネームしてから Bot ユーザーを作成してみたり、管理者権限のあるユーザーで Bot ユーザーを作成してみたけどダメだった...
以前上手くいったのはなんだったのか..

とりあえず一旦 `@feedkun-new` を爆誕させた。
ユーザー名のリネームが浸透していない的な感じだったら後でリネームができるかもしれない

**Comment by masutaka** [comment]
月額 960 円の削減！！１ thx! @tsub :pray:
https://feedforce.slack.com/intl/ja-jp/plans
