### ISSUE TITLE
image me 出来ないのを直す

### ISSUE THREAD

**Issue by masutaka** [feedforce/feedforce-ruboty#62]
https://github.com/feedforce/feedforce-ruboty/pull/61#issuecomment-164392449 参照

**Comment by TasukuNakano** [comment]
Google Developers Consoleでプロジェクトを作成する必要があるのですが、プロジェクト名とかどうしましょうか。
普通に `feedforce` で作ってしまって、技術チームの人たちを追加すればいいですかね。

**Comment by a-know** [comment]
> プロジェクト名

プロジェクトはいくつつくっても問題ないので（作り過ぎるのはあれだけど）、一旦は細かく作っておく、ほうがいいと思っています :+1:

**Comment by masutaka** [comment]
おお、話が進んでいる :+1:

**Comment by TasukuNakano** [comment]
image meできるようになりました。

やったこととしては、https://github.com/feedforce/feedforce-ruboty/pull/61#issuecomment-164392449 に貼った[記事](http://shirakiya.hatenablog.com/entry/2015/12/07/012906)を元に、

* [Google Cloud Platform](https://console.cloud.google.com/project?hl=ja&authuser=0) に `feedforce-ruboty` というプロジェクトを追加しました。
  * 表示された API KEY を `GOOGLE_CSE_KEY` として feedforce-ruboty の環境変数に登録しました
* [Google カスタム検索](https://cse.google.co.jp/cse/all) にて検索エンジンを`ruboty-google_image`という名前で作りました
  * 画像検索をオンにしました
  * 検索するサイトは`追加したサイトを重視して、ウェブ全体を検索する`を選択して、サイトは登録していない状態にしています
  * 検索エンジンIDを `GOOGLE_CSE_ID` として feedforce-ruboty の環境変数に登録しました

inviteなど必要でしたら声をかけていただきたいです。

**Comment by TasukuNakano** [comment]
このissueはcloseしたいと思います

**Comment by masutaka** [comment]
私の方でも image me 確認しました！ :+1: 

> inviteなど必要でしたら声をかけていただきたいです。

お願いします！ masutaka@feedforce.jp です。
